### ISSUE TITLE
Is this project active?

### ISSUE THREAD

**Issue by ghost** [benjcollins/lite-xl-terminal#22]
Hi all.

I want to help, but I want to know if this project is active. *Is this project active?*

**Comment by benjcollins** [comment]
Hi no I really don't have anytime to work on it at the moment and what it needs more than anything is probably a complete rewrite so welcome to fork it or if someone wants to maintain this version I can transfer ownership but as I say the first thing it sorely needs is a rewrite of a lot of the fundamentals.

**Comment by ghost** [comment]
Hi benjcollins.

> Hi no I really don't have anytime to work on it at the moment and what it needs more than anything is probably a complete rewrite so welcome to fork it or if someone wants to maintain this version I can transfer ownership but as I say the first thing it sorely needs is a rewrite of a lot of the fundamentals.

thank you for feedback.
